# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{resque-remora}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{nolan frausto}]
  s.date = %q{2011-12-05}
  s.description = %q{resque plugin that allows you to attach information when a job is put in redis, and to do whatever you want with the information when it is popped off the resque queue}
  s.email = %q{nrfrausto@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/resque-remora.rb",
    "lib/resque/plugins/remora.rb",
    "lib/resque/plugins/remora/push_pop.rb",
    "resque-remora.gemspec",
    "spec/redis-test.conf",
    "spec/resque/plugins/remora/push_pop_spec.rb",
    "spec/resque/plugins/remora_spec.rb",
    "spec/spec_helper.rb",
    "spec/support/jobs.rb"
  ]
  s.homepage = %q{http://github.com/frausto/resque-remora}
  s.licenses = [%q{MIT}]
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.6}
  s.summary = %q{resque plugin that allows you to attach information to a resque job and retrieve it when it gets popped of the queue}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<resque>, ["~> 1.10"])
      s.add_development_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<yajl-ruby>, ["~> 0.8.2"])
      s.add_development_dependency(%q<json>, ["~> 1.5.3"])
    else
      s.add_dependency(%q<resque>, ["~> 1.10"])
      s.add_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<yajl-ruby>, ["~> 0.8.2"])
      s.add_dependency(%q<json>, ["~> 1.5.3"])
    end
  else
    s.add_dependency(%q<resque>, ["~> 1.10"])
    s.add_dependency(%q<rspec>, ["~> 2.3.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<yajl-ruby>, ["~> 0.8.2"])
    s.add_dependency(%q<json>, ["~> 1.5.3"])
  end
end

